routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|->prefix('admin')->as('admin.')
*/
/*
|-----------------------------------------------------------------------------------------
|   location manager
|-----------------------------------------------------------------------------------------
*/
 
 Route::post('/broadcast', 'LocationController@broadcast')->name('broadcast');
  Route::get('/location', 'LocationController@index')->name('location');
  Route::get('set/location', 'LocationController@setlocation')->name('location.set');
  Route::get('/test', 'OrderController@test')->name('test');
/*
|-----------------------------------------------------------------------------------------
|   invite new user by exits user
|-----------------------------------------------------------------------------------------
*/
Route::middleware('auth')->as('user.')->group(function() {
  Route::get('/invite', 'UserController@invite')->name('invite');
  Route::get('/profile', 'UserController@index')->name('profile');
  Route::get('/my-orders', 'UserController@orders')->name('orders');
  Route::get('/my-orders/{order_id}', 'UserController@ordersDetails')->name('orders_details');
  Route::get('/invoice/{order_id}', 'InvoiceController@order_invoice')->name('invoice');
  Route::get('/my-address', 'UserController@address')->name('address');
  Route::get('/my-reviews', 'UserController@reviews')->name('reviews');
  Route::get('/my-coupons', 'UserController@coupons')->name('coupons');
    Route::get('/order-cancell/{id}/{status}', 'OrderController@statusCancel')->name('order.status');
});
/*
|-----------------------------------------------------------------------------------------
|   login & register
|-----------------------------------------------------------------------------------------
*/
  Auth::routes(['verify' => true]);
/*google & fb login*/
  Route::get('/auth/redirect/{provider}', 'Auth\SocialController@redirect')->name('auth2');
  Route::get('login/{provider}/callback','Auth\SocialController@Callback')->name('auth2_callback');
/*confirm register user by mobile/email otp */
  Route::get('/user-confirmation/{id}', 'Auth\RegisterController@userResendMail')->name('user.confirmation');
  Route::post('/login/user/{id}', 'Auth\LoginController@LoginOtp')->middleware("throttle:5,1")->name('login.otp');


//Route::middleware('location')->group(function() {

      Route::get('/', 'HomeController@index')->name('home');
      /*Route::get('/', function () {
          return view('welcome');
      });*/
      Route::get('/home', 'HomeController@index')->name('home');
      Route::get('/mc/{slug}', 'HomeController@master')->name('master');
      Route::get('/search', 'SearchController@index')->name('search');
      Route::get('/store/{type}/{id}/{slug}', 'HomeController@vendor')->name('vendor');
      /*
      |-----------------------------------------------------------------------------------------
      |   Cart
      |-----------------------------------------------------------------------------------------
      */
      Route::get('/cart', 'CartController@index')->name('cart');
      Route::get('/cart/empty', 'CartController@deleteCart')->name('cart.empty');
      /*
      |-----------------------------------------------------------------------------------------
      |   Order
      |-----------------------------------------------------------------------------------------
      */
      Route::get('/checkout', 'OrderController@index')->name('checkout');
      Route::get('/confirm/order', 'OrderController@order')->name('order.confirm');
      Route::get('/order-done/{status}', 'OrderController@thanks')->name('order.done');
      /*
      |-----------------------------------------------------------------------------------------
      |   PAyment
      |-----------------------------------------------------------------------------------------
      */
      Route::get('/payment/{array}', 'PaymentController@index')->name('payment');
      # Call Route
     // Route::get('payumoney', 'PaymentController@payumoney')->name('payumoney');

      # Status Route
      Route::get('payment/status','PaymentController@status')->name('payment.status');
      /*
      |----------------------------------------------------------------------------
      | Other Pages
      |----------------------------------------------------------------------------
      */
      Route::get('/discover-our-world', 'PageController@about')->name('about');
      //Route::get('/our-world', 'PageController@about')->name('team');
      Route::get('/delivery-rider', 'PageController@rider')->name('rider');
      Route::get('/support', 'PageController@contact')->name('contact');
      Route::get('/terms-and-conditions', 'PageController@terms')->name('terms');
      Route::get('/refund-policy', 'PageController@refund')->name('refund');
      Route::get('/privacy-policy', 'PageController@privacy')->name('privacy');
      Route::get('/beware-of-phishing-and-fraud', 'PageController@fraud')->name('fraud');
      
//});

/*
|--------------------------------------------------------------------------
| Admin  Routes
|--------------------------------------------------------------------------
|
*/
    Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('login.admin');    
    /* only 5 request per 1 min for Vendor & Admin Login Post */
    Route::post('/login/admin', 'Auth\LoginController@adminLogin')->middleware("throttle:5,1");    
  
    Route::get('/forget/admin', 'Auth\ForgotPasswordController@showAdminForgetForm')->name('forget.admin');
    Route::post('/forget/admin', 'Auth\ForgotPasswordController@adminForget')->name('forget.admin');



//Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
  //All the admin routes will be defined here...
  
Route::namespace('Admin')->middleware('auth:admin')->prefix('admin')->as('admin.')->group(function() {

  // Auth::routes(['register' => false]);
   Route::get('/', 'HomeController@index')->name('dashboard');
   Route::post('/logout', 'Auth\LoginController@Adminlogout')->name('logout');
   Route::get('/change-password', 'Auth\LoginController@changepassword')->name('change-password');
   Route::post('/update-password', 'Auth\LoginController@updatePassword')->name('update-password');
   /*//////////////////////////////////////////////////////////////////////////*/
  // Route::get('/vendor', 'VendorController@index')->name('vendor');
    Route::get('/add-vendor', 'VendorController@create')->name('add-vendor');
     Route::post('/add-vendor', 'VendorController@store')->name('store-vendor');
      Route::get('/vendor-status/{id}/{status}', 'VendorController@status')->name('vendor.status');
      Route::get('/vendor-verify/{id}/{status}', 'VendorController@verify')->name('vendor.verify');
  // Route::get('/show-vendor/{id}', 'VendorController@show')->name('show-vendor');
   Route::get('/edit-vendor/{id}', 'VendorController@edit')->name('edit-vendor');
   Route::get('/update-vendor/{id}', 'VendorController@update')->name('vendor.update');
   // ///////////////////////////////////////////////////////////
   Route::get('/user', 'UserController@index')->name('user');

   /*////////////////////////////////////////////////////////////////*/
   /*//////////////////////////////////////////////////////////////*/
    Route::get('/city', 'CityController@index')->name('city');
    Route::post('/city/store', 'CityController@store')->name('city.store');
    Route::get('/city/{id}', 'CityController@index')->name('city.edit');
    Route::get('/city/update/{id}', 'CityController@update')->name('city.update');
    //Route::delete('/city/destroy/{id}', 'CityController@destroy')->name('city.destroy');
    /*////////////////////////////////////////////*/
    Route::get('/vertical', 'MasterController@index')->name('master');
    Route::post('/vertical/store', 'MasterController@store')->name('master.store');
    Route::get('/vertical/{id}', 'MasterController@index')->name('master.edit');
    Route::get('/vertical/update/{id}', 'MasterController@update')->name('master.update');
    Route::get('/vertical/{id}/{status}', 'MasterController@status')->name('master.status');
    //Route::delete('/category/destroy/{id}', 'CategorieController@destroy')->name('category.destroy');
    /*////////////////////////////////////////////*/
    Route::get('/category', 'CategorieController@index')->name('category');
    Route::post('/category/store', 'CategorieController@store')->name('category.store');
    Route::get('/category/{id}', 'CategorieController@index')->name('category.edit');
    Route::get('/category/update/{id}', 'CategorieController@update')->name('category.update');
    //Route::delete('/category/destroy/{id}', 'CategorieController@destroy')->name('category.destroy');
    /*/////////////////////////////////////////////////////////////////////////*/
     /*////////////////////////////////////////////*/
    Route::get('/commission', 'CommissionController@index')->name('commission');
    Route::post('/commission/store', 'CommissionController@store')->name('commission.store');
    Route::get('/commission/{id}', 'CommissionController@index')->name('commission.edit');
    Route::get('/commission/update/{id}', 'CommissionController@update')->name('commission.update');
    //Route::delete('/category/destroy/{id}', 'CategorieController@destroy')->name('category.destroy');
    /*/////////////////////////////////////////////////////////////////////////*/
     /*////////////////////////////////////////////*/

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Input;

class UserController extends Controller
{
  function __construct()
  {
      $this->middleware('auth:admin');

  }
  public function index(Request $request)
  {
       $data=DB::table('users')
              ->select('users.*')
              ->paginate(100);

          return View('admin/user/list',compact('data'));
  }

  


}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
 use Illuminate\Support\Str;
    use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    public function login()
    {
        if (Auth::attempt(['email' => request('email'), 'password' => request('password')])) {
            $user = Auth::user();
            $success['token'] = $user->createToken('appToken')->accessToken;
           //After successfull authentication, notice how I return json parameters
            return response()->json([
              'success' => true,
              'token' => $success,
              'user' => $user
          ]);
        } else {
       //if authentication is unsuccessfull, notice how I return json parameters
          return response()->json([
            'success' => false,
            'message' => 'Invalid Email or Password',
        ], 401);
        }
    }

    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
        	'name' => ['required', 'string', 'max:255'],
            'mobile' => ['required', 'string', 'min:10','max:10', 'unique:users'],
            'pincode' => ['required', 'string', 'min:6','max:6'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],

        ]);
        if ($validator->fails()) {
          return response()->json([
            'success' => false,
            'message' => $validator->errors(),
          ], 401);
        }
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $user = User::create($input);
        $success['token'] = $user->createToken('appToken')->accessToken;
        return response()->json([
          'success' => true,
          'token' => $success,
          'user' => $user
      ]);
    }


     public function logout(Request $res)
    {
      if (Auth::user()) {
        $user = Auth::user()->token();
        $user->revoke();

        return response()->json([
          'success' => true,
          'message' => 'Logout successfully'
      ]);
      }else {
        return response()->json([
          'success' => false,
          'message' => 'Unable to Logout'
        ]);
      }
     }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Session;

use App\User;
use App\Address;
use App\Order;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
	function __construct()
    {
    	$this->middleware('auth');
    }

    public function index()
    {
        $user = auth()->user();
        $data=User::where('id',$user->id)->first();
        $address=Address::where('user_id',$user->id)->get();
        $order=DB::table('orders')->where('orders.user_id',$user->id)
                 //->leftJoin('order_items','order_items.order_rid','=','orders.id')
                    ->leftJoin('vendors','vendors.id','=','orders.vendor_id')
                    ->leftJoin('masters','masters.id','=','vendors.masters_id')
                 ->select('orders.*','orders.id as order_rid','orders.status as orders_status',
                    'vendors.company_name as vendor_company_name','masters.name as masters_name',
                    )->get();
         return View('user/profile',compact('data','address','order'));
    }
    public function orders()
    {
        $user = auth()->user();
        $data=DB::table('orders')->where('orders.user_id',$user->id)
                 //->leftJoin('order_items','order_items.order_rid','=','orders.id')
                    ->leftJoin('vendors','vendors.id','=','orders.vendor_id')
                    ->leftJoin('masters','masters.id','=','vendors.masters_id')
                 ->select('orders.*','orders.id as order_rid','orders.status as orders_status',
                    'vendors.company_name as vendor_company_name','masters.name as masters_name','masters.cancellation_till','masters.cancellation_cost'
                    )->get();
         return View('user/order',compact('data'));
    }
     public function ordersDetails($orders_id)
    { 
        $user = auth()->user();
         $data=DB::table('orders')->where('orders.user_id',$user->id)
                ->leftJoin('users','users.id','=','orders.user_id')
               
                ->leftJoin('addresses','addresses.id','orders.user_address_id')
                ->leftJoin('order_items','order_items.order_rid','=','orders.id')
                    ->leftJoin('vendors','vendors.id','=','orders.vendor_id')
                        ->leftJoin('masters','masters.id','=','vendors.masters_id')
                ->leftJoin('product_prices','product_prices.id','=','order_items.product_price_id')
                ->leftJoin('products','products.id','=','product_prices.product_id')
                ->leftJoin('attributes','attributes.id','=','products.attrubute_id')
                    ->leftJoin('riders','riders.id','=','orders.rider_id')
                ->where('orders.order_id',$orders_id)
                ->select('users.name as user_names','users.email as user_email','users.mobile as user_mobile',
                    'addresses.*','orders.*','orders.id as order_rid','orders.status as orders_status',
                    'products.name as product_name','product_prices.qty as product_qty','attributes.name as attributes_name','vendors.company_name as vendor_company_name','masters.name as masters_name',
                    'order_items.id as item_id','order_items.status as item_status',
                    'order_items.cost as item_cost','order_items.discount as item_discount','order_items.price as item_price','order_items.qty as item_qty','order_items.amount as item_amount','riders.name as rider_name'
                    ,'masters.name as masters_name','masters.cancellation_till','masters.cancellation_cost','masters.returnable'
                )->get();
       if(!$data){
            return redirect()->route('user.order')->with('error',' Order Not Found.');
        }
         return View('user/order_details',compact('data'));
    }

    public function address()
    {
        $user = auth()->user();
        $data=Address::where('user_id',$user->id)->get();
        return View('user/address',compact('data'));
    }
    public function reviews()
    {
        $user = auth()->user();
        $data=Address::where('user_id',$user->id)->get();
        return View('user/reviews',compact('data'));
    }
    public function coupons()
    {
        $user = auth()->user();
        $data=Address::where('user_id',$user->id)->get();
        return View('user/coupons',compact('data'));
    }
    public function invite()
    {
        $user = auth()->user();
        $data=User::where('id',$user->id)->first();
        return View('user/invite',compact('data'));
    }


    /* order gaet*/
    public function allAddress()
    {
        $user = auth()->user();
        $id=$user->id;
        $data=Address::where('user_id',$id)->get();      
        
        return response()->json($data);
    }
}

resources/views/user/addRating.blade.php
@extends('layouts.app')
@section('script')
@endsection
@section('content')
<div class="container" style="">
    <div class="main-body">
    
          <div class="row gutters-sm">
            {{-- User Nav --}}
            @include('user.nav')
            {{-- User Nav End --}}
            <div class="col-md-8 tab-content px-3 px-sm-0" id="nav-tabContent">
            	
				
				
                <div class="card mb-3">
                    <div class="card-body" style="margin:1rem;">
                      <div align="center" style="text-align: center;margin-top: 5rem;margin-bottom: 5rem;">
                        <b><span>{{route ('user.invite',Auth::user()->referrer_code) }}</span></b>
                        <p>Share code and Earn ...</p>
                      </div>
                    </div>
                  </div>
        

      {{-- ///////////////////////////// --}}        
             
            </div>
          </div>
        </div>
    </div>
@endsection

@section('style')
<style type="text/css">
.nav-tabs .nav-item{
	text-align: left;
}
.nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
    color: #495057;
    background-color: #f8e7ddcc;
    border-color: #dee2e6 #dee2e6 #dee2e6;
    /*border: 1px solid gray;*/
    font-size: 
}
.nav-tabs .nav-link {
   
    border: 1px solid transparent;
    border-radius: .25rem; 
    /* border-top-right-radius: .25rem; */
}
.main-body {
	
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
</style>
@endsection

resources/views/user/order_details.blade.php
@extends('layouts.app')
@section('script')
@endsection
@section('content')
<div class="container" style="">
    <div class="main-body">
    
          <div class="row gutters-sm">
            {{-- User Nav --}}
            @include('user.nav')
            {{-- User Nav End --}}
            <div class="col-md-8 tab-content px-3 px-sm-0" id="nav-tabContent">
            	
					
				
                
                    
               
				<div class="card mb-3">
                    <a class=" col-2 nav-item nav-link" href="{{ route('user.orders')}}" style="text-align:center;background-color: gray;color: #fff;">Back</a>
<div class="card-body" style="margin:1rem;">
    
@if($data)
    <div class="row text-secondary" style="padding:10px;margin-bottom: 4px;border-bottom: 1px solid gray;">
        <h3 class="col-10">Order <text style="color: black;">#{{$data[0]->order_id}}</text></h3>
        <a class="col-2" href="{{ route('user.invoice',$data[0]->order_id)}}">Invoice</a>
        <div class="col-sm-12" >
          <b>From: {{$data[0]->vendor_company_name}}   ({{$data[0]->masters_name}})</b><br>
          <b>To: {{ $data[0]->address}}, {{ $data[0]->city}}, {{ $data[0]->state}}</b><br>               
        @if($data[0]->item_status==0)
        @endif
        
        @if($data[0]->status==0)
            <b class="status secondary">Pending</b><br>
        @endif
        @if($data[0]->status==11)
            <b class="status secondary">Suggest</b><br>
        @endif
        @if($data[0]->status==1)
            <b  class="status primary">Confirmed</b><br>
        @endif
        @if($data[0]->status==2)
            <b  class="status warning">Baken/Packing</b><br>
        @endif
        @if($data[0]->status==3)
            <b  class="status warning">Dispatch</b><br>
        @endif
        @if($data[0]->status==4)
            <b  class="status primary">Delivered by {{ $data[0]->rider_name}}</b>
            <small>Your item has been delivered</small>
           {{--  <small>Delivered on {{ date('D, d M y, H:i:s A', strtotime($data[0]->created_at)) }}  by {{ $data[0]->rider_name}}</small> --}}<br>
        @endif
        @if($data[0]->status==8)
            <b  class="status secondary">Return</b><br>
        @endif
         @if($data[0]->status==9)
            <b  class="status secondary">Exchange</b><br>
        @endif
        @if($data[0]->status==5)
            <b  class="status text-danger"><b>Cancelled</b></b><br>
        @endif
        @if($data[0]->status==6)
            <b  class="status text-danger"><b>Cancelled</b></b><br>
        @endif
        @if($data[0]->status==7)
            <b  class="status text-danger"><b>Cancelled</b></b><br>
        @endif
        <br>  
        
        {{-- <div class="progress-track">
            <ul id="progressbar">
                <li class="step0 active " id="step1">Ordered</li>
                <li class="step0 active text-center" id="step2">Shipped</li>
                <li class="step0 active text-right" id="step3">On the way</li>
                <li class="step0 text-right" id="step4">Delivered</li>
            </ul>
        </div> --}}
        <small>{{$data[0]->items}} Item</small>           
        </div> 
      
    </div>
    <div class="row text-secondary" style="padding:0px 10px; border-bottom: 1px dotted gray;">
	@foreach($data as $key => $data[0])                            
       	<div class="col-12 row">
            <div class="col-sm-10" >
              <b>{{$data[0]->product_name}} </b>
              <small>&nbsp;<i>( {{ $data[0]->product_qty.' '.$data[0]->attributes_name}} )</i></small>
              &nbsp;<i>X {{ $data[0]->item_qty}}</i>                     
            </div>                        
            {{-- <div class="col-sm-2" >
              <b>&#8377;{{$data[0]->item_cost}}</b>                      
            </div>
            <div class="col-sm-2" >
              <b>{{$data[0]->item_discount}}%</b>                      
            </div> --}}
            <div class="col-sm-2" style="text-align:right">
              <small>&#8377;{{$data[0]->item_amount}}</small>                    
            </div>
        </div>	
    @endforeach
     </div>
    <div class="row text-secondary" style="padding:0px 10px; border-bottom: 1px dotted gray;">
        <div class="col-12 row">
            <div class="col-sm-10" >
              <small>Item Total</small>                   
            </div>                        
            
            <div class="col-sm-2" style="text-align:right">
              <small>&#8377;{{$data[0]->price}}</small>                    
            </div>
        </div>
        <div class="col-12 row" style="">
            <div class="col-sm-10" >
              <small>Delivery partner fee</small>                   
            </div>                        
            
            <div class="col-sm-2" style="text-align:right">
              <small>
                @if($data[0]->shipping==0.00)
                    Free
                @else
                    &#8377;{{$data[0]->shipping}}</small>  
                @endif                 
            </div>
        </div> 
        @if($data[0]->discount!=0.00)
            <div class="col-12 row" style="">
            <div class="col-sm-10" >
              <small>Dicount</small>                   
            </div>                        
            
            <div class="col-sm-2" style="text-align:right">
              <small>&#8377;{{$data[0]->discount}}</small>
            </div>
        </div> 
        @endif
        @if($data[0]->tax!=0.00)
            <div class="col-12 row" style="">
            <div class="col-sm-10" >
              <small>GST</small>                   
            </div>                        
            
            <div class="col-sm-2" style="text-align:right">
              <small>&#8377;{{$data[0]->tax}}</small>
            </div>
        </div> 
        @endif
        <div class="col-12 row" style="border-top: 1px solid black;">
            <div class="col-sm-8" >
              <small>Paid Via @if($data[0]->payment_type==1)Cash @else Online @endif</small>                   
            </div>                        
            <div class="col-sm-2" style="text-align:right">
              <b>  Bill Total</b> 
            </div>
            <div class="col-sm-2" style="text-align:right">
              <b>  &#8377;{{$data[0]->total_amount}}</b> 
            </div>
        </div>
        
        @if($data[0]->status<$data[0]->cancellation_till)
            <div class="col-12 row" style="border-top: 1px solid black;padding: 1rem;">
               <a class="btn btn-danger btn-sm" href="{{ route('user.order.status',['id' => $data[0]->id, 'status' => 5]) }}">Cancel</a>
            </div>
        @endif
         @if($data[0]->status==4)
            <div class="col-12 row" style="border-top: 1px solid black;padding: 1rem;">
               <a class="btn btn-success btn-sm" href="">Re-Order</a>
               @if($data[0]->returnable==1)
                <a class="btn btn-success btn-sm" href="">Return</a>
               @endif
               @if($data[0]->rated==1)               
                <a class="btn btn-success btn-sm" href="">Rating & review</a>
               @endif
            </div>
        @endif

        
    </div> 
		                    	
@else
	<div align="center" style="text-align: center;margin-top: 5rem;margin-bottom: 5rem;">
		<b>No Orders<br>
	          You have not order any product yet!</b>
	</div>
@endif
                			
                		</div>
                	</div>
				
				
					
        

      {{-- ///////////////////////////// --}}        
             
            </div>
          </div>
        </div>
    </div>
@endsection

@section('style')
<style type="text/css">
.nav-tabs .nav-item{
	text-align: left;
}
.nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
    color: #495057;
    background-color: #f8e7ddcc;
    border-color: #dee2e6 #dee2e6 #dee2e6;
    /*border: 1px solid gray;*/
    font-size: 
}
.nav-tabs .nav-link {
   
    border: 1px solid transparent;
    border-radius: .25rem; 
    /* border-top-right-radius: .25rem; */
}
.main-body {
	
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
/*process bar*/


#progressbar {
    margin-bottom: 3vh;
    overflow: hidden;
    color: rgb(252, 103, 49);
    padding-left: 0px;
    margin-top: 3vh
}

#progressbar li {
    list-style-type: none;
    font-size: x-small;
    width: 25%;
    float: left;
    position: relative;
    font-weight: 400;
    color: rgb(160, 159, 159)
}

#progressbar #step1:before {
    content: "";
    color: rgb(252, 103, 49);
    width: 5px;
    height: 5px;
    margin-left: 0px !important
}

#progressbar #step2:before {
    content: "";
    color: #fff;
    width: 5px;
    height: 5px;
    margin-left: 32%
}

#progressbar #step3:before {
    content: "";
    color: #fff;
    width: 5px;
    height: 5px;
    margin-right: 32%
}

#progressbar #step4:before {
    content: "";
    color: #fff;
    width: 5px;
    height: 5px;
    margin-right: 0px !important
}

#progressbar li:before {
    line-height: 29px;
    display: block;
    font-size: 12px;
    background: #ddd;
    border-radius: 50%;
    margin: auto;
    z-index: -1;
    margin-bottom: 1vh
}

#progressbar li:after {
    content: '';
    height: 2px;
    background: #ddd;
    position: absolute;
    left: 0%;
    right: 0%;
    margin-bottom: 2vh;
    top: 0.1rem;/*1px;*/
    z-index: 1
}

.progress-track {
    padding: 0 8%
}

#progressbar li:nth-child(2):after {
    margin-right: auto
}

#progressbar li:nth-child(1):after {
    margin: auto
}

#progressbar li:nth-child(3):after {
    float: left;
    width: 68%
}

#progressbar li:nth-child(4):after {
    margin-left: auto;
    width: 132%
}

#progressbar li.active {
    color: black
}

#progressbar li.active:before,
#progressbar li.active:after {
    background: rgb(252, 103, 49)
}
</style>
@endsection