routes/web.php
    Route::post('/commission/store', 'CommissionController@store')->name('commission.store');
    Route::get('/commission/{id}', 'CommissionController@index')->name('commission.edit');
    Route::get('/commission/update/{id}', 'CommissionController@update')->name('commission.update');
    //Route::delete('/category/destroy/{id}', 'CategorieController@destroy')->name('category.destroy');
    /*/////////////////////////////////////////////////////////////////////////*/
     /*////////////////////////////////////////////*/
    Route::get('/coupon', 'CouponController@index')->name('coupon');
    Route::post('/coupon/store', 'CouponController@store')->name('coupon.store');
    Route::get('/coupon/{id}', 'CouponController@index')->name('coupon.edit');
    Route::get('/coupon/update/{id}', 'CouponController@update')->name('coupon.update');
    //Route::delete('/category/destroy/{id}', 'CategorieController@destroy')->name('category.destroy');
    /*/////////////////////////////////////////////////////////////////////////*/
    Route::get('/subcategory', 'SubCategorieController@index')->name('subcategory');
    Route::post('/subcategory/store', 'SubCategorieController@store')->name('subcategory.store');
    Route::get('/subcategory/{id}', 'SubCategorieController@index')->name('subcategory.edit');
    Route::get('/subcategory/update/{id}', 'SubCategorieController@update')->name('subcategory.update');
   // Route::delete('/subcategory/destroy/{id}', 'SubCategorieController@destroy')->name('subcategory.destroy');
    /*////////////////////////////////////////////*/
    Route::get('/attribute', 'AttributeController@index')->name('attribute');
    Route::post('/attribute/store', 'AttributeController@store')->name('attribute.store');
    Route::get('/attribute/{id}', 'AttributeController@index')->name('attribute.edit');
    Route::get('/attribute/update/{id}', 'AttributeController@update')->name('attribute.update');
    //Route::delete('/attribute/destroy/{id}', 'AttributeController@destroy')->name('attribute.destroy');
     /*////////////////////////////////////////////*/
     /*//////////////////////////////////////////////////////////////////////////////////*/
     //Route::get('/item', 'ProductController@index')->name('item');
     Route::get('/add-item', 'ProductController@create')->name('add-item');
     Route::post('/add-item', 'ProductController@store')->name('store-item');
     Route::get('/edit-item/{id}', 'ProductController@edit')->name('edit-item');
     Route::get('/update-item/{id}', 'ProductController@update')->name('update-item');
     Route::get('/item-status/{id}/{status}', 'ProductController@status')->name('item.status');
     Route::get('/item-featured/{id}/{status}', 'ProductController@featured')->name('item.featured');
     Route::get('/item-verify/{id}/{status}', 'ProductController@verify')->name('item.verify');

     Route::get('/manage-item/{id}', 'ProductController@manage')->name('item.manage');
     Route::post('/manage-item/store/{id}', 'ProductController@manageStore')->name('item.manage.store');
     Route::get('/manage-item/store/{id}', 'ProductController@manageStore')->name('item.manage.store');
     /*//////////////////////////////////////////////////////////////////////////////////*/
   

     Route::get('/vendor-verify/{id}/{status}', 'VendorController@verify')->name('vendor.verify');
   


    /*Reporting*/
    Route::get('/vendor-list', 'ReportController@vendor')->name('vendor-list');
    Route::get('/item-list', 'ReportController@item')->name('item-list');
     Route::get('/item-list', 'ReportController@item')->name('item-list');
      Route::get('/customer-list', 'ReportController@user')->name('customer-list');

      Route::get('/order-list', 'OrderController@index')->name('order-list');
      Route::get('/order-status/{id}/{status}', 'OrderController@status')->name('order.status');
      Route::get('/order-status-all/{id}/{status}/{ostatus}', 'OrderController@statusAll')->name('order.status-all');

      Route::get('/payment-list', 'ReportController@payment')->name('payment-list');
  //****************************************************************************************
  //  Rider
  //******************************************************************************************
    Route::get('/rider-list', 'RiderController@index')->name('rider-list');
    Route::get('/add-rider', 'RiderController@create')->name('add-rider');
     Route::post('/add-rider', 'RiderController@store')->name('store-rider');
     Route::get('/edit-rider/{id}', 'RiderController@create')->name('edit-rider');
      Route::get('/update-rider/{id}', 'RiderController@update')->name('update-rider');
    Route::get('/rider/{id}/{status}', 'RiderController@status')->name('rider.status');
    Route::get('/rider-duty/{id}/{status}', 'RiderController@onDuty')->name('rider.duty');


      Route::get('/assign-rider', 'ReportController@rider')->name('rider.order-list');
      Route::get('/assign-rider/{order_id}', 'ReportController@rider')->name('rider.assign');
      Route::get('/rider-assign/{order_id}', 'RiderController@assign')->name('order-rider-assign');
});

/*
|--------------------------------------------------------------------------
| Vendor Routes
|--------------------------------------------------------------------------
|
*/
	Route::get('/login/vendor', 'Auth\LoginController@showVendorLoginForm')->name('login.vendor');
	 /* only 5 request per 1 min for Vendor & Admin Login Post */
	Route::post('/login/vendor', 'Auth\LoginController@vendorLogin')->middleware("throttle:5,1");

	Route::get('/register/vendor', 'Auth\RegisterController@showVendorRegisterForm')->name('register.vendor');
	Route::post('/register/vendor', 'Auth\RegisterController@createVendor');

  Route::get('/vendor-confirmation/{id}', 'Auth\RegisterController@vendorResendMail')->name('vendor.confirmation');

	Route::get('/vendor-verify/{token}', 'Auth\RegisterController@VendorVerify');
	Route::get('/vendor-rest/{token}', 'Auth\RegisterController@VendorSendPassword');
	Route::get('/vendor-profile-update/{id}', 'Auth\RegisterController@VendorUpdate')->name('vendor-profile-update');

	Route::get('/forget/vendor', 'Auth\ForgotPasswordController@showVendorForgetForm')->name('forget.vendor');
	Route::post('/forget/vendor', 'Auth\ForgotPasswordController@vendorForget')->name('forget.vendor');
  Route::get('/reset-password-vendor/{token}', 'Auth\RegisterController@vendorNewPass');

Route::namespace('Vendor')->middleware('auth:vendor')->prefix('vendor')->as('vendor.')->group(function() {

   Route::post('/logout', 'Auth\LoginController@Vendorlogout')->name('logout');
   Route::get('/change-password', 'Auth\LoginController@changepassword')->name('change-password');
   Route::post('/update-password', 'Auth\LoginController@updatePassword')->name('update-password');

  Route::get('/profile', 'VendorController@profile')->name('profile');
  Route::get('/profile/edit', 'VendorController@edit')->name('profile.edit');
  Route::get('/update/profile', 'VendorController@store')->name('profile.update');

   Route::get('/', 'VendorController@index')->name('dashboard');
   Route::get('/store-status/{status}', 'VendorController@statusStore')->name('store.status');
   Route::get('/add-vendor', 'VendorController@create')->name('add-vendor');
   Route::post('/add-vendor', 'VendorController@store')->name('store-vendor');

     // ///////////////////////////////////////////////////////////////////////
/*//////////////////////////////////////////////////////////////////////////////////*/
   Route::get('/product', 'ProductController@index')->name('product');
   Route::post('/product/store', 'ProductController@store')->name('product.store');

   Route::get('/add-product', 'ProductController@create')->name('add-product');
    Route::post('/product/store2', 'ProductController@create2')->name('product-store2');

 /*  Route::get('/product-status/{id}/{status}', 'ProductController@status')->name('item.status');
    Route::get('/product-featured/{id}/{status}', 'ProductController@featured')->name('item.featured');*/
    /* Route::get('/add-product', 'ProductController@create')->name('add-product');
     Route::post('/add-product', 'ProductController@store')->name('store-product');
     Route::get('/edit-product/{id}', 'ProductController@edit')->name('edit-product');
     Route::get('/update-product/{id}', 'ProductController@update')->name('update-product');*/
     // ///////////////////////////////////////////////////////////////////////
   Route::get('/manage-product/{id}', 'ProductController@manage')->name('product.manage');
   Route::post('/manage-product/store/{id}', 'ProductController@manageStore')->name('product.manage.store');
    Route::get('/manage-product/store/{id}', 'ProductController@manageStore')->name('product.manage.store');
   // Route::get('/manage-product/{id}/{pid}', 'ProductController@manage')->name('product.manage');
     //Route::post('/manage-product/store/{id}/{pid}', 'ProductController@manageStore')->name('product.manage.store');
   // Route::get('/manage-product/update/{id}', 'ProductController@manageStore')->name('product.manage.update');

     /*Reporting*/
    Route::get('/item-list', 'ReportController@item')->name('item-list');
    Route::get('/add-item', 'ProductController@create')->name('add-item');
     Route::post('/add-item', 'ProductController@store')->name('store-item');
     Route::get('/edit-item/{id}', 'ProductController@edit')->name('edit-item');
     Route::get('/update-item/{id}', 'ProductController@update')->name('update-item');

     Route::get('/item-status/{id}/{status}', 'ProductController@status')->name('item.status');
     Route::get('/item-featured/{id}/{status}', 'ProductController@featured')->name('item.featured');
    // Route::get('/item-verify/{id}/{status}', 'ProductController@verify')->name('item.verify');

     Route::get('/manage-item/{id}', 'ProductController@manage')->name('item.manage');

app/Http/Controllers/Vendor/ReportController.php
<?php

namespace App\Http\Controllers\Vendor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Controllers\Input;
use Illuminate\Support\Facades\DB;
use App\Vendor;
use App\User;
use App\Master;

use App\Item;
use App\Product;
use App\City;
use App\Categorie;
use App\Sub_categories;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Arr;

class ReportController extends Controller
{
     function __construct()
    {
        $this->middleware('auth:vendor');

    }
    public function item(Request $request)
    {
        $user = auth()->user();
        $filters = [
                    'search' => 'search',   
                    'products.id' => 'item',
                    'products.categry_id' => 'category',
                    'products.sub_categry_id' => 'subcategory',
                    'products.vendor_id' => 'vendor',
                    'products.status' => 'status',
                    'vendors.city' => 'city',
                  ];
            
        $data=DB::table('products')  
                //->leftJoin('items','items.id','=','products.item_id')
                ->leftJoin('categories','categories.id','=','products.categry_id')
                ->leftJoin('sub_categories','sub_categories.id','=','products.sub_categry_id')
                ->leftJoin('vendors','vendors.id','=','products.vendor_id')
                 ->leftJoin('masters','masters.id','=','products.masters_id')
                 ->leftJoin('attributes','attributes.id','=','products.attrubute_id')
                ->leftJoin('cities','cities.id','vendors.city')
                ->where('products.vendor_id',$user->id)
                ->where(function ($query) use ($request, $filters) {
                        foreach ($filters as $column => $key) {
                            $query->when(Arr::get($request, $key), function ($query, $value) use ($column) {
                                if($column =='search'){
                                    $query->where('products.name','LIKE', '%' . $value . '%')
                                    ->orWhere('products.slug','LIKE', '%' . $value . '%')
                                    ->orWhere('categories.name','LIKE', '%' . $value . '%')
                                    ->orWhere('sub_categories.name','LIKE', '%' . $value . '%')
                                    ->orWhere('cities.name','LIKE', '%' . $value . '%')
                                    ->orWhere('vendors.company_name','LIKE', '%' . $value . '%')
                                    ->orWhere('vendors.address','LIKE', '%' . $value . '%')
                                    ->orWhere('vendors.pin','LIKE', '%' . $value . '%')
                                    ->orWhere('vendors.email','LIKE', '%' . $value . '%');
                                }else{
                                    $query->where($column, $value);
                                }
                            });
                        }
                    })
                ->select('products.id as productsId','products.created_at as pcreated_at','products.*','categories.name as categories_name','sub_categories.name as sub_categories_name',
                    'vendors.name as vendor_name','vendors.email as vendor_email','cities.name as city_name','attributes.name as attributes_name','masters.name as masters_name')
                ->get();
                            
                
        $master=Master::all();
        $vendor=Vendor::all();
         $city=City::all();
          $categry=Categorie::all();
           $subcategry=Sub_categories::all();
         //echo"<pre>",print_r($data),"</pre>";die();
        return view('admin.report.item-list', compact('data','city','categry','subcategry','vendor','request','master'));
    }
}

resources/views/admin/report/item-discount.blade.php
<?php $layouts='layouts.vendor'; ?>

@if(Auth::guard('admin')->check())
@php $layouts='layouts.admin' @endphp
@endif
@if(Auth::guard('vendor')->check())
   @php  $layouts='layouts.vendor' @endphp
@endif

@extends($layouts)

@section('style')
<style type="text/css">
  .text-green{
  color: green;
  font-size: x-large;
  }.text-danger{
  color: red;
  font-size: x-large;
  }
</style>
@endsection


@section('content')


<div class="card ">
  <div class="card-header">
    <div>
      @if(Auth::guard('admin')->check())
        <form method="GET" action="{{ route('admin.item-list') }}">
      @endif
      @if(Auth::guard('vendor')->check())
       <form method="GET" action="{{ route('vendor.item-discount') }}">
      @endif
          
          <div class="form-row">
            @if(Auth::guard('admin')->check())
              <div class="form-group col-md-3">
                  <label for="inputEmail4">Search</label>
                  <input type="text" value="{{ isset($request) ? $request->search : ""}}" name="search" class="form-control"  placeholder="Text">
              </div>
              <div class="form-group col-md-2">
                  <label for="inputEmail4">Master</label>
                  <select value="{{ old('master') }}" name="master" class="form-control select2"  >
                    <option value="">Select Please</option>
                    @foreach($master as $svalue)
                      <option value="{{ $svalue->id }}" {{ isset($request) ? ( $request->master==$svalue->id ? "Selected":"" ) : ""}}>{{ $svalue->name }}</option>
                    @endforeach
                  </select>
              </div>
            @endif
              <div class="form-group col-md-2">
                  <label for="inputEmail4">Category</label>
                  <select value="{{ old('category') }}" name="category" class="form-control"  >
                    <option value="">Select Category</option>
                    @foreach($categry as $svalue)
                      <option value="{{ $svalue->id }}" {{ isset($request) ? ( $request->category==$svalue->id ? "Selected":"" ) : ""}}>{{ $svalue->name }}</option>
                    @endforeach
                  </select>
              </div>
              <div class="form-group col-md-2">
                  <label for="inputEmail4">Sub-Category</label>
                  <select value="{{ old('subcategory') }}" name="subcategory" class="form-control select2"  >
                    <option value="">Select Sub-Category</option>
                    @foreach($subcategry as $svalue)
                      <option value="{{ $svalue->id }}" {{ isset($request) ? ( $request->subcategory==$svalue->id ? "Selected":"" ) : ""}}>{{ $svalue->name }}</option>
                    @endforeach
                  </select>
              </div>
              @if(Auth::guard('admin')->check())
              <div class="form-group col-md-3">
                  <label for="inputEmail4">Vendor</label>
                  <select value="{{ old('vendor') }}" name="vendor" class="form-control select2"  >
                    <option value="">Select Vendor</option>
                    @foreach($vendor as $svalue)
                      <option value="{{ $svalue->id }}" {{ isset($request) ? ( $request->vendor==$svalue->id ? "Selected":"" ) : ""}}>{{ $svalue->name }}</option>
                    @endforeach
                  </select>
              </div>

              <div class="form-group col-md-2">
                  <label for="inputEmail4">City</label>
                  <select value="{{ old('city') }}" name="city" class="form-control select2"  >
                    <option value="">Select City</option>
                    @foreach($city as $svalue)
                      <option value="{{ $svalue->id }}" {{ isset($request) ? ( $request->city==$svalue->id ? "Selected":"" ) : ""}}>{{ $svalue->name }}</option>
                    @endforeach
                  </select>
              </div>
               @endif
              
              
              <div class="form-group col-md-2 float-right" style="padding-top: 1.55rem;">
                <label for="inputEmail4"></label>
                  <button type="submit" class="btn btn-primary ">Submit</button>
                     @if(Auth::guard('admin')->check())
                      <a href="{{ route('admin.item-list') }}" class="btn btn-info ">Reset</a>
                     @endif
                     @if(Auth::guard('vendor')->check())
                      <a href="{{ route('vendor.item-discount') }}" class="btn btn-info ">Reset</a>
                     @endif
              </div>

              <div class="form-group col-md-6 float-right" style="padding-top: 1.55rem;">
               @if(Auth::guard('admin')->check())
                <a class="btn btn-sm btn-info float-right" style="" href="{{ route('admin.add-item') }}"><b>+ Add Item</b></a>
               @endif
               @if(Auth::guard('vendor')->check())
                <a class="btn btn-sm btn-info float-right" style="" href="{{ route('vendor.add-item') }}"><b>+ Add New Item</b></a>
               @endif
                  
              </div>


          </div>                 
          
      </form>
    </div>

  </div>
  <div class="card-body">
    <?php //echo"<pre>",print_r($data),"</pre>";?>
    <div class="table-responsive">
      <form method="GET" action="{{ route('vendor.item-discount-update') }}">
         <div class="form-row">
            
              <div class="form-group col-md-3">
                  <label for="inputEmail4">Discount <i style="color: red;">(%)</i></label>
                  <input type="text" step=".0001" value="" name="discount" required="" class="form-control"  placeholder="Discount">
              </div>
              <div class="form-group col-md-2 float-right" style="padding-top: 1.55rem;">
                <label for="inputEmail4"></label>
                  <button type="submit" class="btn btn-primary ">Submit</button>                    
              </div>
            
          </div>
        <table id="" class="table vtable">
            <thead>
                <tr>
                    <th width="50px"><input type="checkbox" id="allproduct"  class="form-control"></th> 
                 @if(Auth::guard('admin')->check())
                    <th>Date</th>
                 @endif
                    <th>Name</th>
                    
                   @if(Auth::guard('admin')->check())
                    <th>Under Master</th>
                   @endif
                    <th>Under Category</th>
                    <th>Sub-Category</th>
                  @if(Auth::guard('admin')->check())
                    <th>Vendor Name</th>
                    <th>Vendor Email</th>
                    <th>City</th>
                    {{-- <th>Pincode</th> --}}
                  @endif
                    <th>Qty</th>
                    <th>Cost</th>
                    <th>Discount <i style="color: red;">(%)</i></th>
                    <th>Price</th>
                    <th>Action</th>
                    
                    
                </tr>
            </thead>
            <tbody>
            @foreach ($data as $key => $uData)
                <tr>
                    <td><input type="checkbox" name="product[]" class="product form-control" value="{{ $uData->product_price_id }}"></td>
                  @if(Auth::guard('admin')->check())
                    <td>{{ date('d M y', strtotime($uData->pcreated_at)) }}</td>
                  @endif
                    <td>{{ $uData->name }}</td>
                    
                  @if(Auth::guard('admin')->check())
                    <td>{{ $uData->masters_name }}</td>
                  @endif
                    <td>{{ $uData->categories_name }}</td>
                    <td>{{ $uData->sub_categories_name }}</td>
                    @if(Auth::guard('admin')->check())
                      <td> {{$uData->vendor_name}}</td>
                      <td>{{$uData->vendor_email}}</td>
                      <td>{{ $uData->city_name}}</td>
                     {{--  <td>{{ $uData->city_name}}</td> --}}
                    @endif
                      <td>{{ $uData->product_qty}} {{ $uData->attributes_name}}</td>
                      <td>{{ $uData->product_cost}}</td>
                      <td>{{ $uData->product_discount}}</td>
                      <td>{{ $uData->product_price}}</td>
                    
                
                <td style="display: flex;">
                        
                        @if(Auth::guard('vendor')->check())
                        <a href="{{ route('vendor.edit-item',$uData->productsId)}}" class="btn btn-sm btn-primary">Edit</a>
                        <a target="_blank" href="{{ route('vendor.item.manage',$uData->productsId)}}" class="btn btn-sm btn-info">Manage</a> 
                         
                        @endif
                       

                    </td>
                  </tr>
            @endforeach    
                
            </tbody>
          
        </table>
        </form>
        
    </div>
  </div>
  <div class="card-footer text-muted">
{{--     {!! $uData->links() !!} --}}
{{--  {{ $uData->links() }} --}}
  </div>
</div>
	
@endsection

@section('scripts')
<script type="text/javascript">
  $(document).ready(function () {
    
  });
  $(document).ready(function(){
        $('#allproduct').click(function(){
            if($(this).prop("checked") == true){
                console.log("Checkbox is checked.");
                $('.product').each(function() { 
                  this.checked = true; 
                });
            }
            else if($(this).prop("checked") == false){
                console.log("Checkbox is unchecked.");
                $('.product').each(function() {
                  this.checked = false;
                });
            }
        });
    });
</script>  

@endsection

resources/views/admin/report/payment-list.blade.php
@extends('layouts.admin')
@section('scripts')
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script>
$(function() {
  $('input[name="date"]').daterangepicker({
    opens: 'right',
    showDropdowns: true,
    minYear: 1901,
    maxYear: parseInt(moment().format('YYYY'),10),
    locale: {
            format: 'DD-MM-YYYY'
        },
    ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
  }, function(start, end, label) {
    console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  });
});

</script>

@endsection
@section('content')


<div class="card ">
  <div class="card-header">
    <div>
        <form method="GET" action="{{ route('admin.payment-list') }}">
     
          <div class="form-row">
              <div class="form-group col-md-3">
                  <label for="">Date</label>
                 <input type="text" name="date" value="" class="form-control" >
              </div>
              <div class="form-group col-md-3">
                  <label for="">Search</label>
                  <input type="text" value="{{ isset($request) ? $request->search : ""}}" name="search" class="form-control"  placeholder="Text">
              </div>
              <div class="form-group col-md-2">
                  <label for="">Payment Type</label>
                  <select value="" name="payment_type" class="form-control"  >
                    <option value="">Select Status</option>
                    <option value="1" {{ isset($request) ? ( $request->payment_type==1 ? "Selected":"" ) : ""}}>Cash </option>
                    <option value="2" {{ isset($request) ? ( $request->payment_type==2 ? "Selected":"" ) : ""}}>Online </option>
                    
                    </select>
              </div>
              
              <div class="form-group col-md-2">
                  <label for="">Status</label>
                  <select value="" name="status" class="form-control"  >
                    <option value="">Select Status</option>
                    <option value="0" {{ isset($request) ? ( $request->status==0 ? "Selected":"" ) : ""}}>Pending </option>
                    <option value="1" {{ isset($request) ? ( $request->status==1 ? "Selected":"" ) : ""}}>Confirm </option>
                    
                    </select>
              </div>
               
              <div class="form-group col-md-2 float-right" style="padding-top: 1.55rem;">
                <label for=""></label>
                  <button type="submit" class="btn btn-primary ">Submit</button>
                 
                    <a href="{{ route('admin.payment-list') }}" class="btn btn-info ">Reset</a>
                  
              </div>
          </div>                 
          
      </form>
    </div>

  </div>
  <div class="card-body">
    <?php //echo"<pre>",print_r($data),"</pre>";?>
    <div class="table-responsive">
        <table id="" class="table vtable">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Order Id</th>
                    <th>Transition Id</th>
                    <th>Payment Type</th> 
                    <th>Coupon Code</th> 
                    <th>Discount </th> 
                    <th>Delivery</th> 
                    <th>Price </th>
                    <th>Total </th>
                    <th>Tax  </th> 
                    <th>Paid Amount</th>
                    <th>Status</th>
                    <th>Recived Amount</th>          
                  
                    
                </tr>
            </thead>
            <tbody>
            @foreach ($data as $uData)
                <tr>
                    <td>{{ date('d M y', strtotime($uData->created_at)) }}</td>
                    <td>{{ $uData->OD_id }}</td>
                    <td>{{ $uData->transition_id }}</td>
                    <td>
                      @if($uData->payment_type==1)
                       Cash 
                      @elseif($uData->payment_type==2)
                       Online 
                      @endif
                    </td>
                    <td>{{ $uData->coupon_code }}</td>
                    <td>{{ $uData->discount }}</td>
                    <td>&#8377 {{ $uData->shipping }}</td>
                    <td>&#8377 {{ $uData->price }}</td>
                    <td>&#8377 {{ $uData->amount }}</td>
                    <td>&#8377 {{ $uData->tax }}</td>
                    <td><b>&#8377 {{ $uData->total_amount }}</b></td>
                    <td>
                        @if($uData->status==0)
                            <small class="status secondary">Pending</small>
                        @endif                        
                        @if($uData->status==1)
                            <small  class="status primary">Confirm</small>
                        @endif
                    </td>
                    <td><b>&#8377 {{ $uData->recived_amount }}</b></td>
                    
                    
                </tr>
            @endforeach    
                
            </tbody>
           {{--  <tfoot>
                <tr>
                   <th>Id</th>
                    <th>Name</th>
                    
                    <th>Action</th>
                </tr>
            </tfoot> --}}
        </table>

        
    </div>
  </div>
  <div class="card-footer text-muted">
{{--     {!! $uData->links() !!} --}}
{{--  {{ $uData->links() }} --}}
  </div>
</div>
	
   @endsection